### PR TITLE
Bug ethan incorporate changes

### LINKED ISSUE #1004: Create menu options for routes that don't have menu options
Create the following menu options: Log In / Sign Up, My Offers, My Requests, Create Request

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/1004)

*This information is updated automatically. To modify it, please use ZenHub.*

### PR DESCRIPTION
**Pull request by ethanstrominger**
Closes #1004, #1010, #1015

Includes three previous pull requests and incorporates changes from a code review.

### CODE REVIEW

File: web-client/src/modules/create/constants.tsx [hunk 1]
```diff
@@ -1,14 +1,17 @@
...
-
 export enum CreatePostTypes {
   request = 'request',
   offer = 'offer',
 }
+
+export const CreatePostLocation = new Location('/create/:createPostType', {
+  type: Yup.string(),
+});
+export const CreateOfferLocation = new Location(
```
Comment (ashwinkjoseph) [inline web-client/src/modules/create/constants.tsx:12]: why is this required? I don't see it being used anywhere

File: web-client/src/modules/create/constants.tsx [hunk 2]
```diff
@@ -1,14 +1,17 @@
...
+  `/create/post/${CreatePostTypes.offer.valueOf()}`,
+);
+export const CreateRequestLocation = new Location(
```
Comment (ashwinkjoseph) [inline web-client/src/modules/create/constants.tsx:15]: why is this required? I don't see it being used anywhere

File: web-client/src/modules/create/routes.tsx [hunk 3]
```diff
@@ -11,13 +12,16 @@ const CreatePostContainer = lazy(() =>
...
   const { type } = useParams() as Record<string, string>;
-  return <CreatePostContainer type={type as CreatePostTypes} />;
+  return <CreatePostContainer createPostType={type as CreatePostTypes} />;
 };
 
 const Routes = (): ReactElement => (
   <Suspense fallback={<LoadingWrapper />}>
     <Switch>
-      <Route path={CreatePostLocation.path} component={CreatePostPage} />
+      <ProtectedRoute
```
Comment (ashwinkjoseph) [inline web-client/src/modules/create/routes.tsx:21]: don't use protected route here, we need it to be partially protected and the whole module is anyway rendered with partially protected in masterpage

File: web-client/src/modules/requests/constants.tsx [hunk 4]
```diff
@@ -11,6 +11,12 @@ export enum PostTabsType {
 export const AcceptedRequestsLocation = new Location(`${postUrlRoot}/accepted`);
 export const FindRequestsLocation = new Location(`${postUrlRoot}/find`);
 export const OpenRequestsLocation = new Location(`${postUrlRoot}/open`);
-export const ListMyPostsLocation = new Location(`${postUrlRoot}/my/:postType`, {
+export const MyPostsLocation = new Location(`${postUrlRoot}/my/:postType`, {
   postType: Yup.string().required(),
 });
+export const MyOfferPostsLocation = new Location(
```
Comment (ashwinkjoseph) [inline web-client/src/modules/requests/constants.tsx:17]: why is this required? I don't see it being used anywhere

File: web-client/src/modules/requests/constants.tsx [hunk 5]
```diff
@@ -11,6 +11,12 @@ export enum PostTabsType {
...
+  `${postUrlRoot}/my/${PostTabsType.offers.valueOf()}`,
+);
+export const MyRequestPostsLocation = new Location(
```
Comment (ashwinkjoseph) [inline web-client/src/modules/requests/constants.tsx:20]: why is this required? I don't see it being used anywhere

File: web-client/src/modules/requests/routes.tsx [hunk 6]
```diff
@@ -26,23 +27,19 @@ const TabbedPostsPage = lazy(() => import('./pages/TabbedPostsPage'));
...
-        component={AcceptedRequestsContainer}
-        exact
-      />
       <Route
         path={FindRequestsLocation.path}
         component={FindRequestsContainer}
-        exact
       />
-      <Route
+      <ProtectedRoute
```
Comment (ashwinkjoseph) [inline web-client/src/modules/requests/routes.tsx:34]: I wouldn't use protected route here, and would rather have it be controlled by the masterpage.

File: web-client/src/modules/requests/routes.tsx [hunk 7]
```diff
@@ -26,23 +27,19 @@ const TabbedPostsPage = lazy(() => import('./pages/TabbedPostsPage'));
...
+        component={AcceptedRequestsContainer}
+      />
+      <ProtectedRoute
         path={OpenRequestsLocation.path}
         component={OpenRequestsContainer}
-        exact
       />
-      <Route path={ListMyPostsLocation.path} component={TabbedPostsPage} />
-
+      <ProtectedRoute path={MyPostsLocation.path} component={TabbedPostsPage} />
```
Comment (ashwinkjoseph) [inline web-client/src/modules/requests/routes.tsx:42]: I wouldn't use protected route here, and would rather have it be controlled by the masterpage.

**Review by ashwinkjoseph — CHANGES_REQUESTED** [review]
I've requested some changes below.
I think I'd go ahead and make a few of these changes right now as we need some of the changes here for waris and others to start working on the navbar

File: web-client/src/modules/requests/routes.tsx (hunk 6 above)
Comment (ashwinkjoseph) [reply web-client/src/modules/requests/routes.tsx]: let's speak more about this before making this change so for now, I am reverting it

File: web-client/src/modules/requests/routes.tsx (hunk 7 above)
Comment (ashwinkjoseph) [reply web-client/src/modules/requests/routes.tsx]: let's speak more about this before making this change so for now, I am reverting it

**Review by ashwinkjoseph — APPROVED** [review]
LGTM!
